### ISSUE TITLE
wf-metagenomics request

### ISSUE THREAD

**Issue by SilSanGon** [nanoporetech/epi2me-api#34]
Hello,
We are starting with the study of resistance genes, and we are using EPI2ME Desktop and we were very happy because it provided a lot of information very useful. However, if we comparing EPI2ME Agent vs EPI2ME Desktop, EPI2ME Agent analysis Fastq Antimicrobial Resistance showed the taxon to which the resistance gene belongs and the ontolology of the resistance gene, but we can see that this option isn’t in EPI2ME Desktop wf-metagenomics. Is it planned to have these options a nearer future, please?

We are looking forward to hearing from you.

Thank you!

**Comment by shortercode** [comment]
Hi there, thanks for the query. I’ve forwarded it onto our workflow teams. Things are rather busy this week with London Calling but hopefully I’ll be able to get a response for you soon.On 21 May 2024, at 16:47, SilSanGon ***@***.***> wrote:﻿
Hello,
We are starting with the study of resistance genes, and we are using EPI2ME Desktop and we were very happy because it provided a lot of information very useful. However, if we comparing EPI2ME Agent vs EPI2ME Desktop, EPI2ME Agent analysis Fastq Antimicrobial Resistance showed the taxon to which the resistance gene belongs and the ontolology of the resistance gene, but we can see that this option isn’t in EPI2ME Desktop wf-metagenomics. Is it planned to have these options a nearer future, please?
We are looking forward to hearing from you.
Thank you!

**Comment by nggvs** [comment]
Hi @SilSanGon ,
Thank you for using the workflow!
Could you open this feature request in the wf-metagenomics repo: https://github.com/epi2me-labs/wf-metagenomics/issues ?
Thank you very much in advance!

**Comment by SilSanGon** [comment]
Hi @nggvs,

It is done! link: https://github.com/epi2me-labs/wf-metagenomics/issues/99#issue-2325374942

Thank you very much!
